// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenProject;

namespace ScreenProject.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ScreenProject.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<DateTime>("EndTime");

                    b.Property<string>("Occurence");

                    b.Property<int>("Priorty");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("TemplateId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ScreenProject.Models.EventPropereties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId");

                    b.Property<int>("TempfieldId");

                    b.Property<string>("value");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TempfieldId")
                        .IsUnique();

                    b.ToTable("EventProps");
                });

            modelBuilder.Entity("ScreenProject.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BackgroungImg");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("ScreenProject.Models.TemplateProperties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FontFamily");

                    b.Property<int>("FontSize");

                    b.Property<string>("ForeColor");

                    b.Property<int>("LeftMargin");

                    b.Property<string>("PropertyName");

                    b.Property<string>("PropertyType");

                    b.Property<int>("TemplateId");

                    b.Property<int>("TopMargin");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplatesFields");
                });

            modelBuilder.Entity("ScreenProject.Models.Event", b =>
                {
                    b.HasOne("ScreenProject.Models.Template", "Templates")
                        .WithMany("Events")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScreenProject.Models.EventPropereties", b =>
                {
                    b.HasOne("ScreenProject.Models.Event", "Events")
                        .WithMany("EventsProps")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScreenProject.Models.TemplateProperties", "TempFields")
                        .WithOne("EventPropers")
                        .HasForeignKey("ScreenProject.Models.EventPropereties", "TempfieldId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ScreenProject.Models.TemplateProperties", b =>
                {
                    b.HasOne("ScreenProject.Models.Template", "Template")
                        .WithMany("TemplatesFields")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
